# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Andy Osuna
tagline:          'web developer'
description:      'My name is Andrea Gonzalez Osuna, Andy Osuna for short. I am a Web Developer in love with Python and am currently in the delightful city of Tijuana.'
url:              http://andyosuna.com
baseurl:          /

author:
  name:           'Andy Osuna'
  url:            https://twitter.com/andiosuna

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/andyosuna/andyosuna.github.io
