# Dependencies
markdown:         redcarpet
highlighter:      pygments

# permalinks
permalink:        pretty
relative_permalinks: true

# setup
title:            Andy Osuna
tagline:          web developer
description:      'My name is Andrea Gonzalez Osuna, Andy Osuna for short. I am a Web Developer in love with Python and am currently in the delightful city of Tijuana.'
url:              http://andyosuna.com
baseurl:          ''

paginate:         5

# assets
sass:
  sass_dir:       _sass
  style:          :compressed

# about
author:
  name:           'Andy Osuna'
  url:            https://twitter.com/andiosuna
  email:          andyosuna@gmail.com

# custom variables
version:          1.2.0

github:
  repo:           https://github.com/andyosuna/andyosuna.github.io
