# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Django Girls Tijuana
tagline:          'Crea un blog este 7 de marzo'
description:      'Informaci&oacute;n importante sobre el taller de ma&ntilde;ana. Para mas informaci&oacute;n visita <a href="http://djangogirls.org/tijuana" target="_blank">djangogirls.org/tijuana</a><br><br>Made with <3 by <a href="https://twitter.com/andiosuna" target="_blank">@andiosuna</a>.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/andyosuna/andyosuna.github.io
